[package]
name = "rustystore"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
arboard = "3.0"
dirs = "6.0.0"
log = "0.4.28"
env_logger = "0.11.8"
chrono = "0.4.42"
